/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package editor.framework.menuoptionvideo.windowOption;

import editor.framework.documentvideo.interfaces.ICommand;
import editor.framework.documentvideo.products.VideoDocument;
import editor.framework.interfaces.ICore;
import editor.framework.menuoptionvideo.windowOption.commandchange.ChangeFrameControllerHigh;
import editor.framework.menuoptionvideo.windowOption.commandchange.ChangeFrameControllerLow;
import editor.framework.menuoptionvideo.windowOption.commandchange.ChangeFrameControllerMedium;
import editor.framework.menuoptionvideo.windowOption.algorithms.ModeFrameHigh;
import editor.framework.menuoptionvideo.windowOption.algorithms.ModeFrameLow;
import editor.framework.menuoptionvideo.windowOption.algorithms.ModeFrameMedium;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonModel;

/**
 *
 * @author ICAROJ
 */
public class VideoOption extends javax.swing.JFrame {

    /**
     * Creates new form VideoOption
     */
    public VideoOption() {
        initComponents();
        verifyOption();
        List<ICommand> comands = new ArrayList<ICommand>();
        comands.add(new ChangeFrameControllerLow());
        comands.add(new ChangeFrameControllerMedium());
        comands.add(new ChangeFrameControllerHigh());
        controller = new CommandController(comands);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gbtnFrame = new javax.swing.ButtonGroup();
        btnApply = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        rdLow = new javax.swing.JRadioButton();
        rdMedium = new javax.swing.JRadioButton();
        rdHigh = new javax.swing.JRadioButton();
        lbltitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnUndo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnApply.setText("Apply");
        btnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        gbtnFrame.add(rdLow);
        rdLow.setText("Low ");

        gbtnFrame.add(rdMedium);
        rdMedium.setText("Medium");

        gbtnFrame.add(rdHigh);
        rdHigh.setText("High");

        lbltitle.setText("Option frames video:");

        btnUndo.setText("Undo");
        btnUndo.setEnabled(false);
        btnUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUndoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdLow)
                            .addComponent(rdHigh)
                            .addComponent(rdMedium)
                            .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnCancel)
                        .addGap(40, 40, 40)
                        .addComponent(btnApply)
                        .addGap(18, 18, 18)
                        .addComponent(btnUndo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(lbltitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdLow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdMedium)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdHigh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApply)
                    .addComponent(btnCancel)
                    .addComponent(btnUndo))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
      this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyActionPerformed
        verifySelected();
        this.btnUndo.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_btnApplyActionPerformed

    private void btnUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUndoActionPerformed
        controller.undo();
        this.btnUndo.setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_btnUndoActionPerformed

    public final void  verifyOption()
    {
       VideoDocument document = (VideoDocument)ICore.getInstance().getProjectController().getCurrentDoucment();
        if(document.getFrameController() instanceof ModeFrameHigh)
           gbtnFrame.setSelected( rdHigh.getModel(), true);
        else if (document.getFrameController() instanceof ModeFrameMedium )
           gbtnFrame.setSelected( rdMedium.getModel(), true);
        else
           gbtnFrame.setSelected( rdLow.getModel(), true);
    }
    
    private  void verifySelected()
    {
       ButtonModel selected = gbtnFrame.getSelection();
       if(selected.equals(rdLow.getModel()))
         controller.changeFrameControllerLow();
       else if(selected.equals(rdMedium.getModel()))
         controller.changeFrameControllerMedium();
       else if(selected.equals(rdHigh.getModel()))
         controller.changeFrameControllerHigh();
    }

    private static CommandController controller;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApply;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnUndo;
    private javax.swing.ButtonGroup gbtnFrame;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JRadioButton rdHigh;
    private javax.swing.JRadioButton rdLow;
    private javax.swing.JRadioButton rdMedium;
    // End of variables declaration//GEN-END:variables
}
